services:
  backend:
    image: ngocngoc0406/cloud_computing-backend:latest
    container_name: product_app
    ports:
      - "3000:3000"
    environment:
      DB_HOST: "bmt6xnejepmufkqprt0s-mysql.services.clever-cloud.com"
      DB_USER: "ueksyeo4q6ksqmd5"
      DB_PASSWORD: "C5t0PdN0hhGboE6XLhrY"
      DB_NAME: "bmt6xnejepmufkqprt0s"
      PORT: "3000"